.\"@(#)nsdb-remove-nci.8"
.\"
.\" @file doc/man/nsdb-remove-nci.8
.\" @brief man page for nsdb-remove-nci client command
.\"

.\"
.\" Copyright 2011 Oracle.  All rights reserved.
.\"
.\" This file is part of fedfs-utils.
.\"
.\" fedfs-utils is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License version 2.0 as
.\" published by the Free Software Foundation.
.\"
.\" fedfs-utils is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License version 2.0 for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" version 2.0 along with fedfs-utils.  If not, see:
.\"
.\"	http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
.\"
.TH NSDB-REMOVE-NCI 8 "@publication-date@"
.SH NAME
nsdb-remove-nci \- remove NSDB container information from an LDAP server
.SH SYNOPSIS
.B nsdb-remove-nci
.RB [ \-?d ]
.RB [ \-D
.IR binddn ]
.RB [ \-e
.IR nce ]
.RB [ \-l
.IR nsdbname ]
.RB [ \-r
.IR nsdbport ]
.RB [ \-w
.IR bindpw ]
.SH INTRODUCTION
RFC 5716 introduces the Federated File System (FedFS, for short).
FedFS is an extensible standardized mechanism
by which system administrators construct
a coherent namespace across multiple file servers using
.IR "file system referrals" .
For further details, see
.BR fedfs (7).
.P
The bulk of FedFS junction information in a FedFS domain is stored
on one or more LDAP servers.
These servers are known as
.IR "namespace databases" ,
or NSDBs, for short.
.P
FedFS-enabled file servers and clients access the information stored
on NSDBs via standard LDAP queries.
FedFS-enabled file servers use these queries to resolve FedFS junctions.
FedFS administrators use them to manage information
about file sets contained in a FedFS domain name space.
.SH DESCRIPTION
The
.BR nsdb-remove-nci (8)
command is part of a collection of low-level single-use programs that are
intended for testing the NSDB protocol or for use in scripts.
This command is a convenient way to remove NSDB features
from an LDAP server by removing NSDB container information from the server's
.I Directory Information Tree
(or DIT, for short).
.P
The top of the DIT on an LDAP server has one or more
.IR "naming contexts" .
Some LDAP server implementations call these contexts
.IR "root suffixes" .
All LDAP entries on that server are contained under naming contexts.
.P
The root LDAP object under which FedFS-related entries reside
is known as the
.I NSDB Container Entry
(or NCE).
The NCE can be a naming context object,
or it can be located somewhere below the naming context.
Both the naming context and the NCE must be world-readable
for FedFS-enabled clients and servers to access the NSDB.
.P
The
.BR nsdb-remove-nci (8)
command removes the pointer to an NCE from an LDAP server's
naming context entry.
It performs the opposite action from
.BR nsdb-update-nci (8).
The target NCE object and the naming context object
.I must
exist before this operation can complete successfully.
.SH OPTIONS
.IP "\fB\-d, \-\-debug"
Specifies that debugging messages be produced during operation.
.IP "\fB\-?, \-\-help"
Prints an
.BR nsdb-remove-nci (8)
version and usage message on
.IR stderr ,
then exits.
.IP "\fB-D, \-\-binddn=\fIbind-distinguished-name\fP"
Specifies a distinguished name of an entity used to bind to the LDAP server
where the NSDB resides.
If the
.B \-\-binddn
option is not specified,
the value of the FEDFS_NSDB_ADMIN environment variable is consulted.
If this variable is not set,
the NSDB connection parameter database is searched for this DN.
If none of these is specified, or
if this entity does not have permission to modify this area
of the server's DIT, the
.BR nsdb-remove-nci (8)
command fails.
.IP "\fB-e, \-\-nce=\fINSDB-container-entry-distinguished-name\fP"
Specifies the distinguished name of the doomed NSDB Container Entry.
If the
.B \-\-nce
option is not specified,
the value of the FEDFS_NSDB_NCE environment variable is consulted.
If this variable is not set,
then the NSDB connection parameter database is searched for this DN.
If none of these is specified, the
.BR nsdb-remove-nci (8)
command fails.
.IP "\fB\-l, \-\-nsdbname=\fINSDB-hostname\fP"
Specifies the hostname of the NSDB where the NSDB Container Entry resides.
If the
.B \-\-nsdbname
option is not specified,
the value of the FEDFS_NSDB_HOST environment variable is consulted.
If the variable is not set and the
.B \-\-nsdbname
option is not specified, the
.BR nsdb-remove-nci (8)
command fails.
.IP "\fB\-r, \-\-nsdbport=\fINSDB-port\fP"
Specifies the IP port of the NSDB where the NSDB Container Entry resides.
If the
.B \-\-nsdbport
option is not specified,
the value of the FEDFS_NSDB_PORT environment variable is consulted.
The default value if the variable is not set is 389.
.IP "\fB\-w, \-\-bindpw=\fIbinddn-password\fP"
Specifies the password used for simple authentication to the LDAP server
where the NSDB resides
If the
.B \-\-bindpw
option is not specified,
the value of the FEDFS_NSDB_PASSWD environment variable is consulted.
If the variable is not set and the
.B \-\-bindpw
option is not specified, the
.BR nsdb-remove-nci (8)
command asks for a password on
.IR stdin .
Standard password blanking techniques are used
to obscure the password on the user's terminal.
.SH EXIT CODES
The NSDB returns a value that reflects the success of the requested operation.
.TP
.B FEDFS_OK
The LDAP modify request succeeded.
.TP
.B FEDFS_ERR_ACCESS
The bound entity does not have permission to perform the requested operation.
.TP
.B FEDFS_ERR_INVAL
One of the arguments was not valid.
.TP
.B FEDFS_ERR_SVRFAULT
An unanticipated non-protocol error occurred.
.TP
.B FEDFS_ERR_NSDB_ROUTE
The
.BR nsdb-remove-nci (8)
command was unable to find a route to the specified NSDB.
.TP
.B FEDFS_ERR_NSDB_DOWN
The
.BR nsdb-remove-nci (8)
command determined that the specified NSDB was down.
.TP
.B FEDFS_ERR_NSDB_CONN
The
.BR nsdb-remove-nci (8)
command was unable to establish a connection with the specified NSDB.
.TP
.B FEDFS_ERR_NSDB_AUTH
The
.BR nsdb-remove-nci (8)
command was unable to authenticate
and establish a secure connection with the specified NSDB.
.TP
.B FEDFS_ERR_NSDB_LDAP
A non-specific LDAP error occurred on the connection between the
.BR nsdb-remove-nci (8)
command and specified NSDB.
.TP
.B FEDFS_ERR_NSDB_LDAP_VAL
An LDAP error occurred on the connection between the
.BR nsdb-remove-nci (8)
command and specified NSDB.
The specific error may be displayed on the command line.
.TP
.B FEDFS_ERR_NSDB_RESPONSE
The
.BR nsdb-remove-nci (8)
command received a malformed response from the specified NSDB.
.TP
.B FEDFS_ERR_NSDB_FAULT
An unanticipated error related to the specified NSDB occurred.
.TP
.B FEDFS_ERR_NSDB_PARAMS
The local NSDB connection parameter database
does not have any connection parameters on record for the specified NSDB.
.TP
.B FEDFS_ERR_NSDB_LDAP_REFERRAL
The
.BR nsdb-remove-nci (8)
command received an LDAP referral that it was unable to follow.
.TP
.B FEDFS_ERR_NSDB_LDAP_REFERRAL_VAL
The
.BR nsdb-remove-nci (8)
command received an LDAP referral that it was unable to follow.
A specific error may be displayed on the command line.
.TP
.B FEDFS_ERR_NSDB_LDAP_REFERRAL_NOTFOLLOWED
The
.BR nsdb-remove-nci (8)
command received an LDAP referral that it chose not to follow,
either because the local implementation does not support
following LDAP referrals or LDAP referral following is disabled.
.TP
.B FEDFS_ERR_NSDB_PARAMS_LDAP_REFERRAL
The
.BR nsdb-remove-nci (8)
command received an LDAP referral that it chose not to follow
because the local NSDB connection parameter database had no
connection parameters for the NSDB targeted by the LDAP referral.
.SH EXAMPLES
Suppose you are the FedFS administrator of the
.I example.net
FedFS domain and that you want to disable the NCE
.I o=fedfs
on the NSDB
.IR nsdb.example.net .
.RS
.sp
$ nsdb-remove-nci -l nsdb.example.net -D cn=Manager -e o=fedfs
.br
Enter NSDB password:
.br
Successfully removed NCI
.br
.RE
This action does not remove any FedFS records.
It simply removes the pointer to the records.
.SH SECURITY
An entity with appropriate authority, such as an administrator entity,
must be used to modify LDAP entries.
The
.BR nsdb-remove-nci (8)
command must bind as such an entity to perform this operation.
.P
The target LDAP server must be registered in the local NSDB connection
parameter database.
The connection security mode listed
in the NSDB connection parameter database
for the target LDAP server is used during this operation.
See
.BR nsdbparams (8)
for details on how to register an NSDB
in the local NSDB connection parameter database.
.SH "SEE ALSO"
.BR fedfs (7),
.BR nsdb-nces (8),
.BR nsdb-update-nci (8),
.BR nsdbparams (8)
.sp
RFC 5716 for FedFS requirements and overview
.sp
RFC 4510 for an introduction to LDAP
.SH COLOPHON
This page is part of the fedfs-utils package.
A description of the project and information about reporting bugs
can be found at
.IR http://oss.oracle.com/projects/fedfs-utils .
.SH "AUTHOR"
Chuck Lever <chuck.lever@oracle.com>
