/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "fedfs_admin.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <signal.h>
#include <sys/types.h> /* open */
#include <sys/stat.h> /* open */
#include <fcntl.h> /* open */
#include <unistd.h> /* getdtablesize */
#include <memory.h>
#include <sys/resource.h> /* rlimit */
#include <syslog.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

#define _RPCSVC_CLOSEDOWN 120
#define FEDFS_ADMIN_X
extern int _rpcpmstart;		/* Started by a port monitor ? */
 /* States a server can be in wrt request */

#define	_IDLE 0
#define	_SERVED 1
#define	_SERVING 2

static int _rpcsvcstate = _IDLE;	 /* Set when a request is serviced */

static
void _msgout (char* msg)
{
#ifdef RPC_SVC_FG
	if (_rpcpmstart)
		syslog (LOG_ERR, "%s", msg);
	else
		fprintf (stderr, "%s\n", msg);
#else
	syslog (LOG_ERR, "%s", msg);
#endif
}

void
fedfs_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		FedFsCreateArgs fedfs_create_junction_1_arg;
		FedFsPath fedfs_delete_junction_1_arg;
		FedFsLookupArgs fedfs_lookup_junction_1_arg;
		FedFsCreateArgs fedfs_create_replication_1_arg;
		FedFsPath fedfs_delete_replication_1_arg;
		FedFsLookupArgs fedfs_lookup_replication_1_arg;
		FedFsSetNsdbParamsArgs fedfs_set_nsdb_params_1_arg;
		FedFsNsdbName fedfs_get_nsdb_params_1_arg;
		FedFsNsdbName fedfs_get_limited_nsdb_params_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	_rpcsvcstate = _SERVING;
	switch (rqstp->rq_proc) {
	case FEDFS_NULL:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) fedfs_null_1_svc;
		break;

	case FEDFS_CREATE_JUNCTION:
		_xdr_argument = (xdrproc_t) xdr_FedFsCreateArgs;
		_xdr_result = (xdrproc_t) xdr_FedFsStatus;
		local = (char *(*)(char *, struct svc_req *)) fedfs_create_junction_1_svc;
		break;

	case FEDFS_DELETE_JUNCTION:
		_xdr_argument = (xdrproc_t) xdr_FedFsPath;
		_xdr_result = (xdrproc_t) xdr_FedFsStatus;
		local = (char *(*)(char *, struct svc_req *)) fedfs_delete_junction_1_svc;
		break;

	case FEDFS_LOOKUP_JUNCTION:
		_xdr_argument = (xdrproc_t) xdr_FedFsLookupArgs;
		_xdr_result = (xdrproc_t) xdr_FedFsLookupRes;
		local = (char *(*)(char *, struct svc_req *)) fedfs_lookup_junction_1_svc;
		break;

	case FEDFS_CREATE_REPLICATION:
		_xdr_argument = (xdrproc_t) xdr_FedFsCreateArgs;
		_xdr_result = (xdrproc_t) xdr_FedFsStatus;
		local = (char *(*)(char *, struct svc_req *)) fedfs_create_replication_1_svc;
		break;

	case FEDFS_DELETE_REPLICATION:
		_xdr_argument = (xdrproc_t) xdr_FedFsPath;
		_xdr_result = (xdrproc_t) xdr_FedFsStatus;
		local = (char *(*)(char *, struct svc_req *)) fedfs_delete_replication_1_svc;
		break;

	case FEDFS_LOOKUP_REPLICATION:
		_xdr_argument = (xdrproc_t) xdr_FedFsLookupArgs;
		_xdr_result = (xdrproc_t) xdr_FedFsLookupRes;
		local = (char *(*)(char *, struct svc_req *)) fedfs_lookup_replication_1_svc;
		break;

	case FEDFS_SET_NSDB_PARAMS:
		_xdr_argument = (xdrproc_t) xdr_FedFsSetNsdbParamsArgs;
		_xdr_result = (xdrproc_t) xdr_FedFsStatus;
		local = (char *(*)(char *, struct svc_req *)) fedfs_set_nsdb_params_1_svc;
		break;

	case FEDFS_GET_NSDB_PARAMS:
		_xdr_argument = (xdrproc_t) xdr_FedFsNsdbName;
		_xdr_result = (xdrproc_t) xdr_FedFsGetNsdbParamsRes;
		local = (char *(*)(char *, struct svc_req *)) fedfs_get_nsdb_params_1_svc;
		break;

	case FEDFS_GET_LIMITED_NSDB_PARAMS:
		_xdr_argument = (xdrproc_t) xdr_FedFsNsdbName;
		_xdr_result = (xdrproc_t) xdr_FedFsGetLimitedNsdbParamsRes;
		local = (char *(*)(char *, struct svc_req *)) fedfs_get_limited_nsdb_params_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		_rpcsvcstate = _SERVED;
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		_rpcsvcstate = _SERVED;
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		_msgout ("unable to free arguments");
		exit (1);
	}
	_rpcsvcstate = _SERVED;
	return;
}
